version: '3.8'

services:
    dev:
        container_name: nest-api
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
        env_file:
          - .env  
 
networks:
    nesjs-network: